- type: job
  id: BlueshieldOfficer
  name: Blueshield Officer
  description: "Act as a bodyguard and advisor for Command and CentComm VIPs."
  playTimeTracker: JobBlueshieldOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 72000 # 20 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # 15 hrs
  weight: 20
  startingGear: BlueshieldOfficerGear
  icon: "JobIconBlueshield"
  joinNotifyCrew: true
  supervisors: job-supervisors-ntr-centcom
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Command
  - CentralCommand
  - BlueshieldOfficer
  - Service
  - Hydroponics
  - Cargo
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, BluespaceLifelineImplant ] # Go big, or go home.
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: BlueshieldOfficerGear
  equipment:
    eyes: ClothingEyesGlassesBSO
    gloves: ClothingHandsGlovesCombat
    id: BlueshieldPDA
    ears: ClothingHeadsetAltBlueshield
    belt: ClothingBeltAssaultFilled
    pocket1: UniqueBlueshieldOfficerLockerTeleporter
  storage:
    back:
    - Flash
    - ClothingMaskGasSecurity
